server {
    listen 80;
    server_name support-pak.ru www.support-pak.ru;
    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl;
    server_name support-pak.ru www.support-pak.ru;

    ssl_certificate /etc/letsencrypt/live/support-pak.ru/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/support-pak.ru/privkey.pem;

    location /static/ {
        alias /app/static/;
    }

    location / {
        proxy_pass http://web:8000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}
