# Generated by Django 6.0.4 on 2026-04-27 16:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Клиент')),
            ],
            options={
                'verbose_name': 'Клиент',
                'verbose_name_plural': 'Клиенты',
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Контактное лицо')),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('email', models.EmailField(blank=True, max_length=254)),
            ],
            options={
                'verbose_name': 'Контакт',
                'verbose_name_plural': 'Контакты',
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, verbose_name='Локация')),
            ],
            options={
                'verbose_name': 'Локация',
                'verbose_name_plural': 'Локации',
            },
        ),
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Владелец')),
            ],
            options={
                'verbose_name': 'Владелец',
                'verbose_name_plural': 'Владельцы',
            },
        ),
        migrations.CreateModel(
            name='Verification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equipment_type', models.CharField(choices=[('alco', 'Алкотестер'), ('tonometer', 'Тонометр'), ('thermometer', 'Термометр')], max_length=20, verbose_name='Тип оборудования')),
                ('equipment_name', models.CharField(max_length=200, verbose_name='Наименование оборудования')),
                ('status', models.CharField(choices=[('sent', 'Отправлен на поверку'), ('verified', 'Поверен')], default='sent', max_length=20, verbose_name='Статус')),
                ('sent_date', models.DateField(verbose_name='Дата отправки')),
                ('verification_date', models.DateField(blank=True, null=True, verbose_name='Дата поверки')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
            ],
            options={
                'verbose_name': 'Поверка',
                'verbose_name_plural': 'Поверки',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostname', models.CharField(max_length=100, unique=True, verbose_name='Hostname')),
                ('vpn_ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='VPN IP')),
                ('kernel', models.CharField(blank=True, max_length=50)),
                ('x11vnc', models.CharField(blank=True, max_length=5)),
                ('alco', models.CharField(blank=True, max_length=50, verbose_name='Алкотестер')),
                ('tonometer', models.CharField(blank=True, max_length=50, verbose_name='Тонометр')),
                ('software', models.CharField(blank=True, max_length=50, verbose_name='Версия ПО')),
                ('network_speed', models.CharField(blank=True, max_length=20)),
                ('uptime', models.CharField(blank=True, max_length=100)),
                ('hdd', models.FloatField(blank=True, null=True, verbose_name='Свободно ГБ')),
                ('hdd_total', models.FloatField(blank=True, null=True, verbose_name='Всего ГБ')),
                ('hdd_percent', models.FloatField(blank=True, null=True, verbose_name='Занято %')),
                ('anydesk', models.CharField(blank=True, max_length=20, verbose_name='AnyDesk ID')),
                ('sn', models.CharField(blank=True, max_length=50, verbose_name='Серийный номер')),
                ('os', models.CharField(blank=True, max_length=100, verbose_name='ОС')),
                ('ver', models.CharField(blank=True, max_length=10)),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='Последнее обновление')),
                ('last_mqtt_message', models.DateTimeField(blank=True, null=True, verbose_name='Последнее MQTT сообщение')),
                ('is_online', models.BooleanField(default=False, verbose_name='Онлайн')),
                ('offline_since', models.DateTimeField(blank=True, null=True, verbose_name='Оффлайн с')),
                ('in_repair', models.BooleanField(default=False, verbose_name='В ремонте')),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='devices.client', verbose_name='Клиент')),
                ('contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='devices.contact', verbose_name='Контакт')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='devices.location', verbose_name='Локация')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='devices.owner', verbose_name='Владелец')),
            ],
            options={
                'verbose_name': 'Устройство',
                'verbose_name_plural': 'Устройства',
                'ordering': ['hostname'],
            },
        ),
        migrations.CreateModel(
            name='Repair',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('problem', models.TextField(default='', verbose_name='Проблема')),
                ('repair_description', models.TextField(blank=True, null=True, verbose_name='Описание ремонта')),
                ('status', models.CharField(choices=[('created', 'Создан'), ('in_progress', 'В ремонте'), ('ready', 'Готов')], default='created', max_length=20, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата заявки')),
                ('in_progress_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата начала ремонта')),
                ('ready_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата готовности')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Последнее изменение')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='devices.device', verbose_name='Устройство')),
            ],
            options={
                'verbose_name': 'Ремонт',
                'verbose_name_plural': 'Ремонты',
                'ordering': ['-created_at'],
            },
        ),
    ]
