# Generated by Django 6.0.4 on 2026-04-29 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='vpn_ip',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='VPN IP'),
        ),
    ]
