# Generated by Django 6.0.4 on 2026-04-29 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0002_alter_device_vpn_ip'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='cpu_load',
            field=models.FloatField(blank=True, null=True, verbose_name='CPU %'),
        ),
        migrations.AddField(
            model_name='device',
            name='memory_free',
            field=models.FloatField(blank=True, null=True, verbose_name='RAM своб. ГБ'),
        ),
        migrations.AddField(
            model_name='device',
            name='memory_percent',
            field=models.FloatField(blank=True, null=True, verbose_name='RAM %'),
        ),
        migrations.AddField(
            model_name='device',
            name='memory_total',
            field=models.FloatField(blank=True, null=True, verbose_name='RAM всего ГБ'),
        ),
        migrations.AddField(
            model_name='device',
            name='memory_used',
            field=models.FloatField(blank=True, null=True, verbose_name='RAM исп. ГБ'),
        ),
        migrations.AddField(
            model_name='device',
            name='temperature',
            field=models.CharField(blank=True, max_length=20, verbose_name='Температура'),
        ),
        migrations.AddField(
            model_name='device',
            name='uptime_formatted',
            field=models.CharField(blank=True, max_length=100, verbose_name='Аптайм'),
        ),
        migrations.AlterField(
            model_name='device',
            name='anydesk',
            field=models.CharField(blank=True, max_length=50, verbose_name='AnyDesk'),
        ),
        migrations.AlterField(
            model_name='device',
            name='network_speed',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='device',
            name='x11vnc',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
