# Generated by Django 6.0.4 on 2026-06-03 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0003_device_cpu_load_device_memory_free_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='secureboot',
            field=models.CharField(blank=True, max_length=20, verbose_name='Secure Boot'),
        ),
    ]
