# Generated by Django 6.0.4 on 2026-06-18 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0004_device_secureboot'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='broker',
            field=models.CharField(blank=True, max_length=50, verbose_name='Брокер'),
        ),
    ]
