# Generated by Django 6.1.1 on 2026-09-03 10:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0006_device_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.CharField(choices=[('created', 'Создано'), ('online', 'Онлайн'), ('offline', 'Оффлайн'), ('repair_in', 'В ремонт'), ('repair_out', 'Из ремонта')], max_length=20, verbose_name='Событие')),
                ('message', models.CharField(blank=True, max_length=300, verbose_name='Описание')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Время')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='devices.device', verbose_name='ПАК')),
            ],
            options={
                'verbose_name': 'Событие',
                'verbose_name_plural': 'События устройств',
                'ordering': ['-created_at'],
            },
        ),
    ]
