# Generated by Django 6.1.1 on 2026-09-03 10:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0007_deviceevent'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={'verbose_name': 'Объект', 'verbose_name_plural': 'Объекты'},
        ),
        migrations.AlterModelOptions(
            name='device',
            options={'ordering': ['hostname'], 'verbose_name': 'Киоск', 'verbose_name_plural': 'Киоски'},
        ),
        migrations.AlterModelOptions(
            name='deviceevent',
            options={'ordering': ['-created_at'], 'verbose_name': 'Событие', 'verbose_name_plural': 'События киосков'},
        ),
        migrations.AlterField(
            model_name='client',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Объект'),
        ),
        migrations.AlterField(
            model_name='device',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='devices.client', verbose_name='Объект'),
        ),
        migrations.AlterField(
            model_name='deviceevent',
            name='device',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='devices.device', verbose_name='Киоск'),
        ),
        migrations.AlterField(
            model_name='repair',
            name='device',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='devices.device', verbose_name='Киоск'),
        ),
    ]
