# Generated by Django 6.1.1 on 2026-09-03 10:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0008_alter_client_options_alter_device_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='verification',
            name='device',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verifications', to='devices.device', verbose_name='Киоск'),
        ),
        migrations.AddField(
            model_name='verification',
            name='reminded_for',
            field=models.CharField(default='none', max_length=20, verbose_name='Напомнено'),
        ),
        migrations.AddField(
            model_name='verification',
            name='valid_until',
            field=models.DateField(blank=True, null=True, verbose_name='Действует до'),
        ),
    ]
