# Generated by Django 6.1.1 on 2026-09-06 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0014_dailyexam'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='password_migrated',
            field=models.BooleanField(default=False, verbose_name='Пароль мигрирован'),
        ),
    ]
