# Generated by Django 6.1.1 on 2026-09-06 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0015_device_password_migrated'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='vnc_ready',
            field=models.BooleanField(default=False, verbose_name='VNC настроен'),
        ),
    ]
