# Generated by Django 6.1.1 on 2026-09-06 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0016_device_vnc_ready'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='agent_deployed',
            field=models.BooleanField(default=False, verbose_name='info2mqtt загружен'),
        ),
    ]
