# Generated by Django 6.1.1 on 2026-09-11 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0017_device_agent_deployed'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='alco_enabled',
            field=models.BooleanField(blank=True, null=True, verbose_name='Алко включён (конфиг)'),
        ),
        migrations.AddField(
            model_name='device',
            name='tonometer_enabled',
            field=models.BooleanField(blank=True, null=True, verbose_name='Тонометр включён (конфиг)'),
        ),
    ]
