# Generated by Kilo on 2026-09-11
# Добавить флаг включения термометра (sensitecwebcamdetection) в device.
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0018_device_modules_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='thermometer_enabled',
            field=models.BooleanField(blank=True, null=True,
                                      verbose_name='Термометр включён (конфиг)'),
        ),
    ]