# Generated by Kilo on 2026-09-12
# Булев флаг «стандартный киоск» (замена regex-фильтра hostname^\\d{3,}$).
import re

from django.db import migrations, models


def backfill_is_standard(apps, schema_editor):
    Device = apps.get_model('devices', 'Device')
    for device in Device.objects.all().iterator():
        standard = bool(re.fullmatch(r'\d{3,}', device.hostname or ''))
        if bool(device.is_standard) != standard:
            device.is_standard = standard
            device.save(update_fields=['is_standard'])


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0019_device_thermometer_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='is_standard',
            field=models.BooleanField(default=True, verbose_name='Стандартный киоск'),
        ),
        migrations.RunPython(backfill_is_standard, migrations.RunPython.noop),
    ]