# Generated by Django 6.0.4 on 2026-04-29 09:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('devices', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('created', 'Создана'), ('sent', 'Отправлена'), ('delivered', 'Доставлена')], default='created', max_length=20, verbose_name='Статус')),
                ('receiver_name', models.CharField(max_length=200, verbose_name='ФИО получателя')),
                ('receiver_contact', models.CharField(max_length=100, verbose_name='Контакт получателя')),
                ('transport_company', models.CharField(max_length=200, verbose_name='Транспортная компания')),
                ('tracking_number', models.CharField(blank=True, max_length=100, verbose_name='Трек-номер')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создана')),
                ('sent_date', models.DateField(blank=True, null=True, verbose_name='Дата отправки')),
                ('delivered_date', models.DateField(blank=True, null=True, verbose_name='Дата получения')),
                ('description', models.TextField(blank=True, verbose_name='Общее описание')),
                ('device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='devices.device', verbose_name='На какой ПАК')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='devices.location', verbose_name='Локация')),
                ('replacement_device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replacement_for', to='devices.device', verbose_name='Замена на ПАК')),
            ],
            options={
                'verbose_name': 'Отправка',
                'verbose_name_plural': 'Отправки',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ShipmentItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equipment_type', models.CharField(choices=[('thermal_paper', 'Термобумага'), ('batteries', 'Батарейки'), ('tubes', 'Трубочки'), ('mouthpiece', 'Мундштук'), ('printer', 'Принтер'), ('alco', 'Алкотестер'), ('tonometer', 'Тонометр'), ('thermometer', 'Термометр'), ('other', 'Другое')], max_length=30, verbose_name='Тип')),
                ('item_name', models.CharField(blank=True, max_length=200, verbose_name='Название (для Другое)')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Количество')),
                ('description', models.CharField(blank=True, max_length=300, verbose_name='Описание позиции')),
                ('shipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='shipments.shipment', verbose_name='Отправка')),
            ],
            options={
                'verbose_name': 'Позиция отправки',
                'verbose_name_plural': 'Позиции отправки',
            },
        ),
    ]
