# Generated by Django 6.1.1 on 2026-09-03 10:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0008_alter_client_options_alter_device_options_and_more'),
        ('shipments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipment',
            name='device',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='devices.device', verbose_name='На какой Киоск'),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='replacement_device',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replacement_for', to='devices.device', verbose_name='Замена на Киоск'),
        ),
    ]
