# Generated by Django 6.1 on 2026-08-14 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='notify_device_offline',
            field=models.BooleanField(default=False, verbose_name='Уведомлять о падении ПАК'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='notify_device_online',
            field=models.BooleanField(default=False, verbose_name='Уведомлять о возврате ПАК'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='notify_health_check',
            field=models.BooleanField(default=False, verbose_name='Уведомлять о health-check'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='notify_weekly_report',
            field=models.BooleanField(default=False, verbose_name='Уведомлять о еженедельной сводке'),
        ),
    ]
