# Generated by Django 6.1.1 on 2026-09-03 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_userprofile_notify_device_offline_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='notify_device_offline',
            field=models.BooleanField(default=False, verbose_name='Уведомлять о падении Киоск'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='notify_device_online',
            field=models.BooleanField(default=False, verbose_name='Уведомлять о возврате Киоск'),
        ),
    ]
