# Generated by Django 6.1.1 on 2026-09-03 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_userprofile_notify_device_offline_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='notify_verification_expiry',
            field=models.BooleanField(default=False, verbose_name='Уведомлять о сроках поверок'),
        ),
    ]
