# Generated by Django 6.1.1 on 2026-09-03 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_userprofile_notify_verification_expiry'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='bot_admin',
            field=models.BooleanField(default=False, verbose_name='Может добавлять пользователей через бот'),
        ),
    ]
