"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 6.1.
"""

from pathlib import Path
import os

try:
    from dotenv import load_dotenv
    load_dotenv(Path(__file__).resolve().parent.parent / '.env')
except ImportError:
    pass

BASE_DIR = Path(__file__).resolve().parent.parent

# Секреты берутся из переменных окружения (см. .env.example).
# Значения по умолчанию ниже нужны только для локальной разработки.
SECRET_KEY = os.getenv('DJANGO_SECRET_KEY', 'django-insecure-замени-на-свой-надёжный-ключ')
DEBUG = os.getenv('DJANGO_DEBUG', 'False') == 'True'
ALLOWED_HOSTS = os.getenv(
    'DJANGO_ALLOWED_HOSTS',
    'support-pak.ru,www.support-pak.ru,192.168.0.113,localhost'
).split(',')
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
CSRF_TRUSTED_ORIGINS = os.getenv(
    'DJANGO_CSRF_TRUSTED_ORIGINS',
    'https://support-pak.ru,https://www.support-pak.ru'
).split(',')

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'devices',
    'shipments',
    'accounts',
    'tickets',
    'bot',
    'trips',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.middleware.gzip.GZipMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'core.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'core.wsgi.application'

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': os.getenv('DB_NAME', 'device_hub'),
        'USER': os.getenv('DB_USER', 'devicehub'),
        'PASSWORD': os.getenv('DB_PASSWORD', 'securepassword'),
        'HOST': os.getenv('DB_HOST', 'localhost'),
        'PORT': os.getenv('DB_PORT', ''),
    }
}

TELEGRAM_BOT_TOKEN = os.getenv('TELEGRAM_BOT_TOKEN', '')

# MQTT-подключение (используется management-командами)
MQTT_BROKER = os.getenv('MQTT_BROKER', '77.239.107.241')
MQTT_PORT = int(os.getenv('MQTT_PORT', '1883'))
MQTT_USER = os.getenv('MQTT_USER', 'pak')
MQTT_PASS = os.getenv('MQTT_PASS', '')
# Топики статусных сообщений ПАК (через запятую). Узкая подписка вместо
# '#' — листенер не читает весь брокер, а только свои префиксы.
MQTT_TOPIC = os.getenv('MQTT_TOPIC', 'client/#,pak/#')

# Отдельный брокер для суточных снимков осмотров (если он отличается от
# статусного брокера). Пустой MQTT_DAY_BROKER — day-подключение не запускается.
MQTT_DAY_BROKER = os.getenv('MQTT_DAY_BROKER', '')
MQTT_DAY_PORT = int(os.getenv('MQTT_DAY_PORT', str(MQTT_PORT)))
MQTT_DAY_USER = os.getenv('MQTT_DAY_USER', MQTT_USER)
MQTT_DAY_PASS = os.getenv('MQTT_DAY_PASS', MQTT_PASS)
MQTT_DAY_TOPICS = os.getenv('MQTT_DAY_TOPICS', 'pak/day,client/day')

# Доступ по SSH к киоскам (используется в views.py)
DEVICE_SSH_USER = os.getenv('DEVICE_SSH_USER', 'terminal')
DEVICE_SSH_PASSWORD = os.getenv('DEVICE_SSH_PASSWORD', '')
# Пароль VNC (x0vncserver) на ПАК. По умолчанию — стандартный SSH-пароль.
DEVICE_VNC_PASSWORD = os.getenv('DEVICE_VNC_PASSWORD', DEVICE_SSH_PASSWORD)
# Пароль sudo/root на ПАК, если он отличается от пароля входа по SSH.
# Пустой — sudo выполняется паролем входа.
DEVICE_SSH_SUDO_PASSWORD = os.getenv('DEVICE_SSH_SUDO_PASSWORD', '')
# Публичные SSH-ключи (сервер + личные, например с Мака, НЕ git), через запятую.
# Добавляются в authorized_keys пользователя terminal при смене пароля ПАК.
DEVICE_SSH_PUBLIC_KEYS = [
    k.strip() for k in os.getenv('DEVICE_SSH_PUBLIC_KEYS', '').split(',') if k.strip()
]
# Ключи device.conf для включения/выключения модулей ПАК.
# ВКЛ = строка закомментирована (#), ВЫКЛ = активна со значением false.
DEVICE_MODULE_TOGGLE_KEYS = {
    'alco': 'dingo.params.enabled',
    'tonometer': 'andble.params.enabled',
    'thermometer': 'sensitecwebcamdetection.params.enabled',
}
# Резервные SSH-пароли (через запятую): пробуются по очереди, если у киоска
# не задан свой пароль и глобальный не подошёл.
DEVICE_SSH_PASSWORDS = [p for p in os.getenv('DEVICE_SSH_PASSWORDS', '').split(',') if p.strip()]

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

LANGUAGE_CODE = 'ru-ru'
TIME_ZONE = 'Europe/Moscow'
USE_I18N = True
USE_TZ = True

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

CACHES = {
    'default': {
        # Учитывая несколько gunicorn-воркеров, используем общий кэш в БД,
        # чтобы rate-limit логина работал одинаково для всех процессов.
        'BACKEND': 'django.core.cache.backends.db.DatabaseCache',
        'LOCATION': 'django_cache',
    }
}

# Логи телеметрии (mqtt_listener2) должны быть видны в `docker compose logs`.
# По умолчанию root-логгер — WARNING, поэтому info-сообщения листенера
# (подключение, day-снимки, ошибки разбора) подавлялись. Выводим их в console.
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {'format': '{asctime} {levelname} {name} {message}', 'style': '{'},
    },
    'handlers': {
        'console': {'class': 'logging.StreamHandler', 'formatter': 'verbose'},
    },
    'loggers': {
        'devices.mqtt': {'handlers': ['console'], 'level': 'INFO', 'propagate': False},
    },
}

SESSION_COOKIE_HTTPONLY = True
SESSION_COOKIE_SAMESITE = os.getenv('DJANGO_SESSION_COOKIE_SAMESITE', 'Lax')
# В проде (TLS перед nginx) по умолчанию включаем secure-cookie и HSTS;
# в разработке — off, чтобы не ломать локальный http. Переопределяется env.
_secure_default = 'True' if not DEBUG else 'False'
SESSION_COOKIE_SECURE = os.getenv('DJANGO_SESSION_COOKIE_SECURE', _secure_default) == 'True'
CSRF_COOKIE_SECURE = os.getenv('DJANGO_CSRF_COOKIE_SECURE', _secure_default) == 'True'
SECURE_HSTS_SECONDS = int(os.getenv('DJANGO_HSTS_SECONDS', '31536000' if not DEBUG else '0'))
SECURE_HSTS_INCLUDE_SUBDOMAINS = (
    os.getenv('DJANGO_HSTS_INCLUDE_SUBDOMAINS', 'True' if not DEBUG else 'False') == 'True')

LOGIN_URL = '/accounts/login/'
LOGIN_REDIRECT_URL = '/dashboard/'
LOGOUT_REDIRECT_URL = '/accounts/login/'

STATIC_URL = '/static/'
STATICFILES_DIRS = [BASE_DIR / 'static']
STATIC_ROOT = BASE_DIR / 'staticfiles'
