# Generated by Django 6.1.1 on 2026-09-03 10:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0008_alter_client_options_alter_device_options_and_more'),
        ('tickets', '0002_activitylog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='device',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='devices.device', verbose_name='Киоск'),
        ),
    ]
