# Generated by Django 6.0.4 on 2026-06-04 15:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('devices', '0004_device_secureboot'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата поездки')),
                ('description', models.TextField(verbose_name='Что сделано')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='devices.device', verbose_name='ПАК (если относится)')),
            ],
            options={
                'verbose_name': 'Поездка СТОЛИЦА',
                'verbose_name_plural': 'Поездки СТОЛИЦА',
                'ordering': ['-date'],
            },
        ),
    ]
