# Generated by Django 6.0.4 on 2026-06-04 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0004_device_secureboot'),
        ('trips', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trip',
            name='device',
        ),
        migrations.AddField(
            model_name='trip',
            name='devices',
            field=models.ManyToManyField(blank=True, to='devices.device', verbose_name='ПАКи'),
        ),
    ]
