# Generated by Django 6.1.1 on 2026-09-03 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0008_alter_client_options_alter_device_options_and_more'),
        ('trips', '0002_remove_trip_device_trip_devices'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='devices',
            field=models.ManyToManyField(blank=True, to='devices.device', verbose_name='Киоски'),
        ),
    ]
